# Generated by Django 5.0.13 on 2025-08-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('sysnr', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_tables', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='erp_tables_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_tables', to='connection.connection')),
            ],
        ),
        migrations.CreateModel(
            name='objects',
            fields=[
                ('obj_id', models.AutoField(primary_key=True, serialize=False)),
                ('obj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=255, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_project', to='connection.project')),
            ],
            options={
                'unique_together': {('project_id', 'obj_name')},
            },
        ),
        migrations.CreateModel(
            name='fields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('sap_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('fields', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('isMandatory', models.CharField(blank=True, max_length=255, null=True)),
                ('isKey', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_objid', to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_projid', to='connection.project')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='connection.project'),
        ),
        migrations.CreateModel(
            name='segments',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('segement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extraction_last_changed', models.DateTimeField(blank=True, null=True)),
                ('validation_last_changed', models.DateTimeField(blank=True, null=True)),
                ('validation_version', models.CharField(blank=True, max_length=255, null=True)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segement_objid', to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segement_projid', to='connection.project')),
            ],
        ),
        migrations.CreateModel(
            name='SaveRule',
            fields=[
                ('rule_no', models.AutoField(primary_key=True, serialize=False)),
                ('source_table', models.CharField(blank=True, max_length=255, null=True)),
                ('source_field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_mapping_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data_mapping_rules', models.CharField(blank=True, max_length=500000, null=True)),
                ('target_sap_table', models.CharField(blank=True, max_length=255, null=True)),
                ('target_sap_field', models.CharField(blank=True, max_length=255, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('lookup_table', models.CharField(blank=True, max_length=255, null=True)),
                ('lookup_field', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('isKey', models.CharField(blank=True, max_length=255, null=True)),
                ('check_box', models.BooleanField(default=False)),
                ('isMandatory', models.CharField(blank=True, max_length=255, null=True)),
                ('user_mandatory', models.BooleanField(blank=True, default=False, null=True)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.fields')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.project')),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.segments')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_no', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.CharField(blank=True, max_length=255, null=True)),
                ('version_id', models.IntegerField()),
                ('source_table', models.CharField(blank=True, max_length=255, null=True)),
                ('source_field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_mapping_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data_mapping_rules', models.CharField(blank=True, max_length=500000, null=True)),
                ('target_sap_table', models.CharField(blank=True, max_length=255, null=True)),
                ('target_sap_field', models.CharField(blank=True, max_length=255, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('lookup_table', models.CharField(blank=True, max_length=255, null=True)),
                ('lookup_field', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('isKey', models.CharField(blank=True, max_length=255, null=True)),
                ('check_box', models.BooleanField(default=False)),
                ('isMandatory', models.CharField(blank=True, max_length=255, null=True)),
                ('user_mandatory', models.BooleanField(blank=True, default=False, null=True)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.project')),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.segments')),
            ],
        ),
        migrations.AddField(
            model_name='fields',
            name='segement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_segementid', to='connection.segments'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_time', models.TextField()),
                ('message', models.TextField()),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.project')),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.segments')),
            ],
        ),
        migrations.CreateModel(
            name='FileConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileType', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet', models.CharField(blank=True, max_length=255, null=True)),
                ('tableName', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='connection.project')),
            ],
            options={
                'unique_together': {('project_id', 'fileName')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('project_id', 'connection_name')},
        ),
    ]
