# Generated by Django 5.0.13 on 2025-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
