# Generated by Django 5.0.13 on 2025-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_objects_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='segments',
            name='selection_criteria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
