# Generated by Django 5.0.13 on 2025-09-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_segments_selection_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saverule',
            name='lookup_field',
        ),
        migrations.RemoveField(
            model_name='saverule',
            name='lookup_table',
        ),
        migrations.AddField(
            model_name='saverule',
            name='lookup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
