# Generated by Django 5.0.13 on 2025-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_remove_saverule_lookup_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='lookup_field',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='lookup_table',
        ),
        migrations.AddField(
            model_name='rule',
            name='lookup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
