# Generated by Django 5.0.13 on 2025-09-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_remove_rule_lookup_field_remove_rule_lookup_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='lookup_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='lookup_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saverule',
            name='lookup_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saverule',
            name='lookup_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
